name: CNN
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pre-commit
  - setuptools
  - pytest
  - cookiecutter
  - sphinx
  - matplotlib
  - jupyter
  - scikit-learn
  - pandas
  - flake8
  - pathlib
  - python=3.8
  - tensorflow
  - xarray
  - ipykernel
  - python-cdo
  - dask
  - prefect
